### PR TITLE
Display a sample anecdote on the homepage

### LINKED ISSUE #2: Add anectodes
Ideally, as a carousel with individual quotes.

### PR DESCRIPTION
**Pull request by Vinnl**
As per @corinalogan's request: https://mobile.twitter.com/LoganCorina/status/981834006500167680

Note that you will probably want to clean up some anecdotes, such as

> My account can be found here: https://socialbat.org/2015/08/12/goals-of-science-vs-goals-of-scientists-a-love-letter-for-plos-one/

Also note that I'm currently linking to the Signatories page, as I presume all anecdotes will be shown there?

Fixes #2.

### CODE REVIEW

**Comment by Vinnl** [comment]
Oh, and another remark: this obviously doesn't work when the user has Javascript disabled. In that case, the quote section will simply not be displayed at all, and the website will look as it did before.

**Comment by lgatto** [comment]
Thank you @Vinnl. That's really great. Not sure whether we would prefer a dedicated page for anecdotes or to display them all at the bottom of the signature page. What do you think @corinalogan?

**Comment by Vinnl** [comment]
I've updated it so you can add the anecdote to whatever page you wish, as follows:

```
{% include anecdote.html %}
````

**Comment by lgatto** [comment]
Thank you so much. Your twitter profile say "Helping academic communities achieve open access." I certainly think that, however minor this contribution is, is a genuine support to academics getting a message of openness and inclusivity out there.

**Comment by Vinnl** [comment]
It was a nicely scoped distraction from the more ambitious project that is Flockademic :)

If I can be of help again in the future, let me know.

**Comment by corinalogan** [comment]
Hey! Answering your question @lgatto would it be easier to list the compiled anecdotes at the bottom of the signature page? I think it would work because it's really similar to what we are doing now. 

Also, if I need to clean the anecdotes of identifying information, is there a file I should use to do this and if so where should I post it? 

@Vinnl you have been so amazing! How can we pay you and how much? We do have a small budget for this so just let me know.

**Comment by Vinnl** [comment]
@corinalogan Consider it a friendly service from one open science project to another - I know how hard it is to obtain funds :) I'm sure Flockademic will benefit from your work in the future one way or another as well.

Note that identifying information is not the problem anymore (it is public now anyway), but it just looks a bit odd displaying that as an anecdote about the need for open science.

**Comment by corinalogan** [comment]
@Vinnl wow thank you so so much!!! If there is anything we can do for you in the future, just let us know!

Thanks also for the note about the identifying information.

**Pull request merged**
